### ISSUE TITLE
intermittent failure to load remotes

### ISSUE THREAD

**Issue by gwenbu-ms** [alex-vukov/module-federation-import-remote#18]
We've encountered a few cases where a remote fails to load in one attempt but succeeds in several surrounding attempts (such as in a retry grouping). In all cases, the error thrown is `Loading script failed...`, which is the error message when `event.type` is something other than `load` (ref: loadRemote()). Our API logs tell us that the correlating requests are succeeding. All data suggests that something we don't understand is happening either in the library or in webpack or in the connection to the remote API (that isn't showing up in logs).

Can we bug you to enrich the error message with more info about the actual event so that we can better troubleshoot what's happening in these cases? It would be helpful to know what the actual event type is, and any other relevant details on the event as well.

Thanks tons!

**Comment by alex-vukov** [comment]
Hi @gwenbu-ms. I have extended the error to include the error.type too. You can get it in the newest version of the library 1.0.24. Unfortunately the error information is a bit limited. The types can only be "load", "error" or "timeout". You are most likely hitting a timeout. By default the webpack script loader adds a timeout of 120 milliseconds so it's possible that your requests sometime exceed that time.

**Comment by gwenbu-ms** [comment]
Thanks! If there is additional context in the `error` events, we'd love to surface that too. But this is a great start - appreciate the support!

**Comment by gwenbu-ms** [comment]
This change has been useful - thanks! We're seeing event type 'error' on occasion, and we'd find it super helpful to surface any additional context in the event for troubleshooting. Any chance you might be able to add error event details (message, etc) to that same `Loading script failed...` error message please?

**Comment by alex-vukov** [comment]
The underlying __webpack_require__.l function which loads the scripts is pretty simple. It just adds a new <script> tag in the head of the current page which triggers an attempt from the browser to load it. If the load is successful the script tag is then removed. Otherwise you get the error. You have a network issue which is causing your problem but __webpack_require__.l does not provide more detailed information for me to extend. Maybe you can try pinging the server continuously or enabling some logs on it.
